### ISSUE TITLE
What does this module do? 

### ISSUE THREAD

**Issue by webmaster94** [stwlam/adequate-vision#1]
Can you provide a more detailed explanation of what this module actually does? The DnD 5e System already implements darkvision. Does this module automatically change the vision mode when the character sheet has darkvision or does it alter the vision system in some way? 

I apologize if I am missing something but your readme is not exactly clear.

**Comment by benbarbour** [comment]
I like the "link actor senses" idea quite a bit, but I agree with the other part of this issue too - the README could use a bit of elaboration on what exactly "fewer unwelcome visual surprises and is more in tune with dnd5e rules" actually means.
