### ISSUE TITLE
Darkvision not desaturated.

### ISSUE THREAD

**Issue by Ikabodo** [stwlam/adequate-vision#13]
It seems to me that darkvision desaturated and monochrome?

I guess this could be by design? But I'll put it here to be safe. :)

![image](https://user-images.githubusercontent.com/7766890/197387356-69a62bf9-93cb-476a-af08-20d7e3348db3.png)

**Comment by stwlam** [comment]
The scene isn't dark. Desaturation kicks in once scene darkness increases.
