### ISSUE TITLE
Darkvision when with other modules

### ISSUE THREAD

**Issue by YenBenGrey** [stwlam/adequate-vision#33]
Hello there, 

In a scene where there is no light source and the setting is set to tokens have vision, the tokens with darkvision are seeing in colour, unless I reduce the Darkness overlay level to about 0.65 or below. 

I have tested this by turning AV off and leaving PV and Less Fog on, and the token is seeing in grey with the Darkness overlay at 0. 

Foundry 10.291
DND5e 2.1.5
AV 0.2.1

**Comment by stwlam** [comment]
That is precisely how it is intended to work

**Comment by YenBenGrey** [comment]
Why are they seeing in colour when there’s no light source?

The problem I’ve got is that when you set the darkness overlay to anything above 0.6, and then as GM I look through the eyes of a token, which means I have click on the token, I can’t see the rest of the map because it’s too dark!

Even with Less Fog, this only lightens the Fog not the darkness overlay. 

Therefore I can’t click a token then move them anywhere because I can’t see where to move them to. 

Please can there be an option to turn this off for some folk in settings? 

All the other stuff in AV I could use. Especially the auto setting of vision for tokens. That’s fantastic.
