### ISSUE TITLE
See Invisibility and other custom vision types

### ISSUE THREAD

**Issue by rotjeking7** [stwlam/adequate-vision#39]
Would it be possible for you to create a short video showing the exact steps of creating a token with the ability to see invisibility? 

I have tried several times, have created an active effect with the name "See Invisibility", also tried adding the vision "See invisibility" with an effect. Neither work for me. All regulars vision work without issue, it is just the special ones that you added through a script. 

I also checked my token with a console log and got the expected results for the effects, but nothing changed for the senses. Just as a sidenote, I am using the correct version of Foundry. I also should not have any other modules that are causing issues. The only other vision module I am using is perfect vision. 

```
for (const effect of actor.effects) {
    console.log(effect.label )  //See Invisibility is show
    console.log(effect.disabled || effect.isSuppressed)  // false is  shown
}
console.log(actor.system.attributes.senses) // Special remains empty, others are shown as normal. Also made sure both tokens were in light and had vision enabled. But it still could not see the invisible token. 
```

Hope you could help me make it work.

**Comment by stwlam** [comment]
I can take a look at this later today.
