### ISSUE TITLE
Feature Request: Darkness Rendered as Dim Light within Darkvision Radius

### ISSUE THREAD

**Issue by Dumbhuman** [stwlam/adequate-vision#6]
As I understand the 5e Darkvision rules there are three effects that happen within the Darkvision range:

1. Dim Light within the Darkvision range is seen as Bright Light.
2. Darkness within the Darkvision range is seen as Dim Light.
3. Darkness within the Darkvision range is seen as black and white rather than color.

The default behavior in DnD5e v.2.0.3 seems to correctly handle point 3 and partially addresses point 1, but fails to put a range limit on that effect.  Your module thankfully enforces the correct range for point 1, but point 2 is still incorrect as Darkness within range is currently displaying as Bright Light.

Below is a scene in Foundry VTT v10.288 running DnD5e v2.0.3 and using Adequate Vision v0.0.3 as the only module enabled:
![image](https://user-images.githubusercontent.com/63615591/195429620-d0fbb831-28af-404c-9b3b-dc0a1126884e.png)
By setting Vision Brightness to 1, the Dim Light area within Darkvision range looks equivalent to the Bright Light area, however the Darkness area within Darkvision range looks exactly the same.  It should look equivalent to the Dim Light area around the light.

Compared to the same scene with your module turned off, it's obviously a big improvement (no modules enabled below):
![image](https://user-images.githubusercontent.com/63615591/195433533-35da283a-44f7-46f0-87aa-018ea89b884a.png)

Ideally though, I'd hope for point 2 to be addressed so that things can look like this similar scene in Foundry VTT v9.280 running DnD5e v1.6.3 and using Perfect Vision v3.9.15 (plus its dependency LibWrapper v1.12.8.0) as the only modules enabled:
![image](https://user-images.githubusercontent.com/63615591/195435686-05ad7494-1a54-4299-b688-7456a5ab44d0.png)

Things are definitely much improved in v10 with your module enabled and if you're able to get Darkness within the Darkvision range to display as Dim Light instead of Bright Light then we'll be able to have rules-accurate Darkvision for DnD5e within Foundry again!

**Comment by stwlam** [comment]
Adequate Vision's darkvision implementation intentionally doesn't set brightness to 1 but at a compromise position of 0.75. The difference is stark in your screenshots but less so with a background.

**Comment by Dumbhuman** [comment]
Here's a screenshot with Vision Brightness set to 0.75 and using a cavern background that's typical of an area where Darkvision would be used.  The Dim Light provided by Darkvision's range still appears to be the same brightness as the Bright Light provided by Darkvision's range:
![image](https://user-images.githubusercontent.com/63615591/195664564-e3d863a3-c377-4263-adbc-08089ea5300d.png)

If I set the Vision Brightness slider to 0, the Dim Light provided by Darkvision's range much more closely matches the Dim Light provided only by the light source outside of Darkvision's range, but unfortunately the Bright Light provided by Darkvision also looks just as dim:
![image](https://user-images.githubusercontent.com/63615591/195665069-d46d93f6-c11a-43bc-b521-1c7f358366b1.png)

Is there any way your module could perhaps provide a separate setting for Vision Brightness in Darkness and Vision Brightness in Dim Light?  Or, likely simpler*, perhaps mask Vision Brightness to only apply in areas where light already exists?  Below is a mockup combining the two previous screenshots into what I imagine Adequate Darkvision could ideally provide:
![image](https://user-images.githubusercontent.com/63615591/195667585-bad1f688-38e7-42db-8673-048e5f1cdcef.png)

That addition to Adequate Vision would bring Darkvision within range of what can be achieved in v9 with the Perfect Vision module as shown below:
![image](https://user-images.githubusercontent.com/63615591/195668827-41fd0746-9400-48c3-a77d-da2c0b4f85b3.png)
 

( * I'm sure none of this stuff is actually simple, but I just imagine it's more work to introduce two separate Vision Brightness settings.  If it were possible though, it would give users a lot of options to customize how effective they'd like Darkvision to be. )

**Comment by stwlam** [comment]
I can tweak the defaults a bit to get it closer, but one of the reasons why this is "adequate vision" is it's a best effort without doing some deeper hacking of V10 vision and detection modes.

**Comment by Dumbhuman** [comment]
I hear you.  I'm not a coder so I don't know how complex the solutions are, but I understand if they're outside this module's intended scope.  I wouldn't worry about tweaking the defaults for my sake if you're happy enough with them, because I expect I'll be staying on v9 until such time as the DnD5e system in v10 can provide Darkvision that's a bit closer to what I've been able to use in previous Foundry versions.

**Comment by stwlam** [comment]
Closing: by the time upstream makes the necessary changes, this won't need to be addressed by the module.
